from __future__ import division, absolute_import
""" Actor for mirrors (via Galil devices).
"""
import functools
import sys
import traceback

import numpy
from twistedActor import Actor, CommandError, log, CommandQueue, UserCmd
from RO.Comm.TwistedTimer import Timer

from .const import convOrient2MMRad
from .version import __version__

__all__ = ["MirrorCtrl", "runMirrorCtrl"]

DefaultMaxUsers = 5

class MirrorCtrl(Actor):
    """Mirror controller actor
    """
    def __init__(self,
        device,
        userPort,
        maxUsers = DefaultMaxUsers,
        name = 'MirrorCtrl',
        doConnect = True,
    ):
        """Create a Galil mirror controller actor

        @param[in] device    A Galil device from galilDevice.py
        @param[in] userPort  port on which to listen for client connections
        @param[in] maxUsers  maximum allowed simultaneous users
        @param[in] doConnect: if True then connect devices on construction
        """
        self.statusTimer = Timer() # used to queue status after stop and reset commands,
            # giving the axes time to halt before status is sent
        Actor.__init__(self,
            userPort = userPort,
            devs = [device],
            maxUsers = maxUsers,
            version = __version__,
            name = name,
            doConnect = doConnect,
            doDevNameCmds = False,
        )
        self.galil = device # easier access
        def killFunc(killThisCmd, killedByCmd):
            log.info("%r queued, killing executing %r" % (killedByCmd, killThisCmd))
            # add a stop command to the queue (will be inserted in queue before killedByCmd)
            killThisCmd.setState(killThisCmd.Done)
            userCmd = UserCmd()
            userCmd.cmdVerb = 'stop'
            userCmd._cmdStr = 'stop (autogenerated by killFunc)'
            self.cmdQueue.addCmd(userCmd, self.galil.cmdStop)

        self.cmdQueue = CommandQueue(
            killFunc=killFunc,
            priorityDict = {
                "stop" : CommandQueue.Immediate,
                "reset" : CommandQueue.Immediate,
                "move" : 3,
                "home" : 3,
                "status" : 1,
                "showparams" : 1,
            }
        )
        self.cmdQueue.addRule(
            action = CommandQueue.KillRunning, # note this will also cancel a queued move
            newCmds = ['move'],
            queuedCmds = ['move'],
        )
        self.cmdQueue.addRule(
            action = CommandQueue.CancelNew,
            newCmds = ['move'],
            queuedCmds = ['home'],
        )
        self.cmdQueue.addRule(
            action = CommandQueue.CancelNew,
            newCmds = ['home'],
            queuedCmds = ['move'],
        )
        self.cmdQueue.addRule(
            action = CommandQueue.CancelNew,
            newCmds = ['status'],
            queuedCmds = ['status'],
        )
        self.cmdQueue.addRule(
            action = CommandQueue.CancelNew,
            newCmds = ['showparams'],
            queuedCmds = ['showparams'],
        )

    def _cancelTimers(self):
        """Cancel all timers
        """
        self.cmdQueue.queueTimer.cancel()
        self.statusTimer.cancel()

    # def logMsg(self, msgStr):
    #     """Write a message string to the log.

    #     @param[in] msgStr: message to be written to log
    #     """
    #     log.info(msgStr)

    def processOrientation(self, orientation):
        """Convert a user specified orientation in um and arcseconds with possibly < 5
        fields specified into an orientation of 5 values in units of radians and mm.

        @param[in] orientation: [Piston (um), [Tilt X ("), [Tilt Y ("), [Trans X (um), [Trans Y (um)]]]]]
        @return numpy.array([Piston (mm), Tilt X (rad), Tilt Y (rad), Trans X (rad), Trans Y (rad)])
        """
        orientation = numpy.hstack((orientation, numpy.zeros(5-len(orientation))))
        return convOrient2MMRad(orientation)

    def cmd_galil(self, cmd):
        """Send an arbitrary command to the Galil mirror controller. Do not put quotes around the command.

        The Galil accepts multiple commands on one line, separated by a semicolon.
        The entire line of command should result in exactly one "OK" being printed at the end,
        e.g. either by ending with a single "XQ#..." command or with MG "OK".
        However, if neither appears to be present, then '; MG "OK"' is appended.

        Note: this replaces twistedActor.Actor's default support for direct device commands,
        because we want the command to be managed by the command queue.

        @param[in] cmd: new local user command (twistedActor.UserCmd)
        """
        if not cmd or not cmd.cmdArgs:
            raise CommandError("No command specified")
        # if this command does not contain MG "OK" or and XQ# add an MG "OK" to force
        # command completion after sending
        cmdStr = cmd.cmdArgs
        if cmdStr.endswith(";"):
            cmdStr = cmdStr[:-1]

        lastCmd = cmdStr.rsplit(";", 1)[-1].replace(" ", "")
        forceOK = True
        if lastCmd.startswith("XQ#") or lastCmd == 'MG"OK"':
            # last command is an XQ# command (all of which end by outputting OK) or explicitly outputs OK
            forceOK = False
        if forceOK:
            cmdStr += '; MG "OK"'

        try:
            self.cmdQueue.addCmd(cmd, functools.partial(self.galil.runCommand, galilCmdStr=cmdStr))
        except Exception, e:
            traceback.print_exc(file=sys.stderr)
            raise CommandError(str(e))
        return True
        cmd.setState(cmd.Done)

    def cmd_move(self, cmd):
        """Move mirror to a commanded orientation, if device isn't busy.

        @param[in] cmd: new local user command (twistedActor.UserCmd)

        Pass 1-5 comma seperated arguements.  Order of arguemnts corresponds to:
        [Piston (um), Tilt X ("), Tilt Y ("), Trans X (um), Trans Y (um)]

        Non-specified orientation values are commanded as zeros. When an orientation
        is specified for a non adjustable degree of freedom (eg, 3.5m tert translation),
        it is silently replaced with the constrained value (typically nearly zero).
        """
        if not cmd or not cmd.cmdArgs:
            raise CommandError("No orientation specified")
        try:
            cmdArgList = numpy.asarray(cmd.cmdArgs.split(","), dtype=float)
        except Exception:
            raise CommandError("Could not parse %s as a comma-separated list of floats" % (cmd.cmdArgs,))
        if not (0 < len(cmdArgList) < 6):
            raise CommandError("Must specify 1 to 5 orientation values; got %s" % (len(cmdArgList)))
        if not self.galil.conn.isConnected:
            raise CommandError("Device Not Connected")

        # convert orientation to mm and radians, padding with zeros as needed
        cmdOrient = self.processOrientation(cmdArgList)
        try:
            self.cmdQueue.addCmd(cmd, functools.partial(self.galil.cmdMove, orient=cmdOrient))
        except Exception, e:
            traceback.print_exc(file=sys.stderr)
            raise CommandError(str(e))

        return True

    def cmd_offset(self, cmd):
        """Offset mirror orientation by the commanded amount, if device isn't busy

        @param[in] cmd: new local user command (twistedActor.UserCmd)

        Pass 1-5 comma seperated arguements.  Order of arguemnts corresponds to:
        [Piston (um), Tilt X ("), Tilt Y ("), Trans X (um), Trans Y (um)]

        Non-specified orientation values are commanded as zeros. When an orientation
        is specified for a non adjustable degree of freedom (eg, 3.5m tert translation),
        it is silently replaced with the constrained value (typically nearly zero).
        """
        if not cmd or not cmd.cmdArgs:
            raise CommandError("No orientation offset specified")
        try:
            cmdArgList = numpy.asarray(cmd.cmdArgs.split(","), dtype=float)
        except Exception:
            raise CommandError("Could not parse %s as a comma-separated list of floats" % (cmd.cmdArgs,))
        if not (0 < len(cmdArgList) < 6):
            raise CommandError("Must specify 1 to 5 orientation values; got %s" % (len(cmdArgList)))
        if not self.galil.conn.isConnected:
            raise CommandError("Device Not Connected")

        currOrient = self.galil.status.orient[0:5]
        if not numpy.all(numpy.isfinite(currOrient)):
            raise CommandError("Current orientation unknown")

        # convert commanded delta- orientation to mm and radians, padding with zeros as needed
        # and add to current orientation to get commanded orientation
        cmdOrient = self.processOrientation(cmdArgList) + currOrient
        try:
            self.cmdQueue.addCmd(cmd, functools.partial(self.galil.cmdMove, orient=cmdOrient))
        except Exception, e:
            traceback.print_exc(file=sys.stderr)
            raise CommandError(str(e))

        return True

    def cmd_home(self, cmd):
        """Home specified axes (e.g. A, B, C); home all axes if none specified

        @param[in] cmd: new local user command (twistedActor.UserCmd)
        """
        # split on , and strip leading and trailing whitespace to make a list of single axis letters
        axisList = [arg.strip() for arg in cmd.cmdArgs.split(",") if arg.strip()]
        for arg in axisList:
            if len(arg) != 1:
                raise CommandError(
                    "Could not parse %s as a comma-separated list of letters" % (cmd.cmdArgs,))
        if not self.galil.conn.isConnected:
            raise CommandError("Device Not Connected")
        try:
            self.cmdQueue.addCmd(cmd, functools.partial(self.galil.cmdHome, axisList = axisList))
        except Exception, e:
            raise CommandError(str(e))
        return True

    def cmd_status(self, cmd):
        """Show status of Galil mirror controller

        @param[in] cmd: new local user command (twistedActor.UserCmd)
        """
        # twistedActor status
        Actor.cmd_status(self, cmd)
        if not self.galil.conn.isConnected:
            raise CommandError("Device Not Connected")
        try:
            if self.cmdQueue.currExeCmd.cmd.isDone:
                # put a status command on the stack
                self.cmdQueue.addCmd(cmd, self.galil.cmdStatus)
            else:
                # currently executing a command, send a cached status
                self.galil.cmdCachedStatus(cmd)
        except Exception, e:
            raise CommandError(str(e))
        return True

    def cmd_showparams(self, cmd):
        """Show parameters of Galil mirror controller

        @param[in] cmd: new local user command (twistedActor.UserCmd)
        """
        if not self.galil.conn.isConnected:
            raise CommandError("Device Not Connected")
        try:
            self.cmdQueue.addCmd(cmd, self.galil.cmdParams)
        except Exception, e:
            raise CommandError(str(e))
        return True

    def cmd_stop(self, cmd):
        """Abort any executing Galil command, put Galil in known state

        @param[in] cmd: new local user command (twistedActor.UserCmd)
        """
        if not self.galil.conn.isConnected:
            raise CommandError("Device Not Connected")
        try:
            self.cmdQueue.addCmd(cmd, self.galil.cmdStop)
        except Exception, e:
            raise CommandError(str(e))
        # command a status for 1 second later (roughly 2x stopping time from max speed)
        dummyCmd = UserCmd(cmdStr="%i status" % cmd.userID)
        dummyCmd.cmdVerb = "status"
        dummyCmd.userID = cmd.userID
        self.statusTimer.start(1., self.cmdQueue.addCmd, dummyCmd, self.galil.cmdStatus)
        return True

    def cmd_reset(self, cmd):
        """Reset the Galil using an 'RS' command.

        @param[in] cmd: new local user command (twistedActor.UserCmd)
        """
        if not self.galil.conn.isConnected:
            raise CommandError("Device Not Connected")
        try:
            self.cmdQueue.addCmd(cmd, self.galil.cmdReset)
        except Exception, e:
            raise CommandError(str(e))
        dummyCmd = UserCmd(cmdStr="%i status"%cmd.userID)
        dummyCmd.cmdVerb = "status"
        dummyCmd.userID = cmd.userID
        self.statusTimer.start(1., self.cmdQueue.addCmd, dummyCmd, self.galil.cmdStatus)
        return True


def runMirrorCtrl(name, device, userPort):
    """Start up a Galil actor

    @param[in] name: name of controller, e.g. "sec35m"; used for the log file and log entries
    @param[in] device: a twistedActor-based Galil Device (see mirrorCtrl/galilDevice.py)
    @param[in] userPort: port on which actor accepts user commands
    """
    from twisted.internet import reactor
    from twistedActor import startSystemLogging

    # if LogDir is specified as an environment variable, begin logging to it.
    if name == "tert35m":
        startSystemLogging("LOCAL2")
    else:
        startSystemLogging("LOCAL3")

    MirrorCtrl(
        name = name,
        device = device,
        userPort = userPort,
    )
    reactor.run()
